export default [
  {
    key: 1,
    name: "Cola",
    theme: "Softdrink",
    kind: "Normal",
    price: 2.0,
    alcohol: 0.0,
  },
  {
    key: 2,
    name: "Cola Zero",
    theme: "Softdrink",
    kind: "Zero",
    price: 2.0,
    alcohol: 0.0,
  },
  {},
  {
    key: 3,
    name: "Cola Light",
    theme: "Softdrink",
    kind: "Light",
    price: 2.0,
    alcohol: 0.0,
  },
  {
    key: 4,
    name: "Fanta",
    theme: "Softdrink",
    kind: "Normal",
    price: 2.0,
    alcohol: 0.0,
  },
  {
    key: 5,
    name: "Fanta Zero",
    theme: "Softdrink",
    kind: "Zero",
    price: 2.0,
    alcohol: 0.0,
  },
  {
    key: 6,
    name: "Fanta Light",
    theme: "Softdrink",
    kind: "Light",
    price: 2.0,
    alcohol: 0.0,
  },
  {
    key: 7,
    name: "Sprite",
    theme: "Softdrink",
    kind: "Normal",
    price: 2.0,
    alcohol: 0.0,
  },
  {
    key: 8,
    name: "Sprite zero",
    theme: "Softdrink",
    kind: "Zero",
    price: 2.0,
    alcohol: 0.0,
  },
  {
    key: 9,
    name: "Sprite Light",
    theme: "Softdrink",
    kind: "Light",
    price: 2.0,
    alcohol: 0.0,
  },
  {
    key: 10,
    name: "Water",
    theme: "Softdrink",
    kind: "Normal",
    price: 2.0,
    alcohol: 0.0,
  },
  {
    key: 11,
    name: "Soda Water",
    theme: "Softdrink",
    kind: "Normal",
    price: 2.0,
    alcohol: 0.0,
  },
  {
    key: 12,
    name: "Ice Tea",
    theme: "Softdrink",
    kind: "Normal",
    price: 2.0,
    alcohol: 0.0,
  },
  {
    key: 13,
    name: "Ice Tea Zero",
    theme: "Softdrink",
    kind: "Normal",
    price: 2.0,
    alcohol: 0.0,
  },
  {
    key: 14,
    name: "Coffee",
    theme: "Hotdrink",
    kind: "Normal",
    price: 2.0,
    alcohol: 0.0,
  },
  {
    key: 15,
    name: "Tea",
    theme: "Hotdrink",
    kind: "Normal",
    price: 2.0,
    alcohol: 0.0,
  },
  {
    key: 16,
    name: "Jupiler",
    theme: "Beer",
    kind: "Pils",
    price: 2.5,
    alcohol: 5.9,
  },
  {
    key: 17,
    name: "Jupiler 0.0%",
    theme: "Beer",
    kind: "Non-alcoholic",
    price: 2.5,
    alcohol: 0.0,
  },
  {
    key: 18,
    name: "Vedett",
    theme: "Beer",
    kind: "Pils",
    price: 5.2,
    alcohol: 5.9,
  },
];
